# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
timezone:         Europe/Berlin
title:            'Dein Mittagessen'
tagline:          'Lunchelot Blog'
description:      ''
url:              http://blog.lunchelot.de
baseurl:          /

author:
  name:           'Lunchelot'
  url:            https://lunchelot.de

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems:
  - jekyll-redirect-from
