# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Lunchelot
tagline:          'Lunchelot Blog'
description:      'Der Lunchelot Blog - Wenns um Dein Mittagessen geht.<br /> Social: <br /> <a href="https://twitter.com/LunchelotDE" target="_blank">@LunchelotDE</a> <a href="https://www.facebook.com/pages/Lunchelot/817285571685255" target="_blank">Facebook</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
